In [1]:
import numpy as np

In [7]:
my_list1=[1,2,3,4]


In [8]:
my_array1= np.array(mylist1)

In [9]:
my_array1

array([1, 2, 3, 4])

In [13]:
my_list2=[11,22,33,44]

In [14]:
my_lists = [my_list1,my_list2]

In [15]:
my_array2=np.array(my_lists)

In [16]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [17]:
my_array2.shape

(2, 4)

In [18]:
my_array2.dtype

dtype('int32')

In [21]:
 np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
my_zeros_array= np.zeros(5)

In [23]:
my_zeros_array.dtype

dtype('float64')

In [24]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.empty(5)

array([1.60219306e-306, 2.44763557e-307, 1.69119330e-306, 8.45599366e-307,
       1.37962388e-306])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])