In [1]:
import numpy as np


In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

to form a random array with random distribution of numbers we use
A= np.random.randn(value)
where random stands for random numbers
and randn stands for random normal distribution 

In [5]:
A= np.random.randn(10)

A

array([ 0.71168348,  0.22747978,  1.06026615,  0.10631905,  0.68679399,
       -0.46252397, -0.35707199,  0.79891515, -0.17327787, -0.55762662])

In [6]:
B = np.random.randn(10)
B

array([-0.49695132,  1.57820046,  0.85795938,  2.09063214,  0.38989871,
        1.313818  ,  0.87216148,  1.5708201 , -0.50982346,  2.03321469])

In [7]:
# Binary function

In [8]:
np.add(A,B)

array([ 0.21473216,  1.80568024,  1.91822553,  2.19695119,  1.0766927 ,
        0.85129403,  0.5150895 ,  2.36973525, -0.68310133,  1.47558807])

In [9]:
np.maximum(A,B)

array([ 0.71168348,  1.57820046,  1.06026615,  2.09063214,  0.68679399,
        1.313818  ,  0.87216148,  1.5708201 , -0.17327787,  2.03321469])

In [11]:
website ='https://mail.google.com/mail/u/7/#inbox'
import webbrowser
webbrowser.open(website)

True